// Real destinations data with actual places and information
const realDestinations = [
  {
    id: 'paris-france',
    name: 'Paris',
    country: 'France',
    description: 'The City of Light, famous for the Eiffel Tower, Louvre Museum, and romantic atmosphere.',
    image: 'https://images.unsplash.com/photo-1502602898536-47ad22581b52?w=800&q=80',
    rating: 4.7,
    visitorsCount: '38M annually',
    bestTime: 'April to October',
    category: 'city',
    highlights: ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame', 'Champs-Élysées', 'Arc de Triomphe'],
    coordinates: { lat: 48.8566, lng: 2.3522 },
    currency: 'EUR',
    language: 'French',
    timeZone: 'CET'
  },
  {
    id: 'tokyo-japan',
    name: 'Tokyo',
    country: 'Japan',
    description: 'Modern metropolis blending ancient traditions with cutting-edge technology.',
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
    rating: 4.8,
    visitorsCount: '15M annually',
    bestTime: 'March to May, September to November',
    category: 'city',
    highlights: ['Shibuya Crossing', 'Senso-ji Temple', 'Mount Fuji', 'Tokyo Skytree', 'Tsukiji Market'],
    coordinates: { lat: 35.6762, lng: 139.6503 },
    currency: 'JPY',
    language: 'Japanese',
    timeZone: 'JST'
  },
  {
    id: 'bali-indonesia',
    name: 'Bali',
    country: 'Indonesia',
    description: 'Tropical paradise with stunning beaches, rice terraces, and Hindu temples.',
    image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&q=80',
    rating: 4.6,
    visitorsCount: '6M annually',
    bestTime: 'April to September',
    category: 'beach',
    highlights: ['Ubud Rice Terraces', 'Mount Batur', 'Tanah Lot Temple', 'Seminyak Beach', 'Monkey Forest'],
    coordinates: { lat: -8.3405, lng: 115.0920 },
    currency: 'IDR',
    language: 'Indonesian',
    timeZone: 'WITA'
  },
  {
    id: 'new-york-usa',
    name: 'New York City',
    country: 'United States',
    description: 'The city that never sleeps, home to Broadway, Central Park, and the Statue of Liberty.',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80',
    rating: 4.6,
    visitorsCount: '65M annually',
    bestTime: 'April to June, September to November',
    category: 'city',
    highlights: ['Statue of Liberty', 'Central Park', 'Times Square', 'Brooklyn Bridge', 'Empire State Building'],
    coordinates: { lat: 40.7128, lng: -74.0060 },
    currency: 'USD',
    language: 'English',
    timeZone: 'EST'
  },
  {
    id: 'london-uk',
    name: 'London',
    country: 'United Kingdom',
    description: 'Historic capital with royal palaces, world-class museums, and iconic landmarks.',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80',
    rating: 4.5,
    visitorsCount: '30M annually',
    bestTime: 'March to May, September to November',
    category: 'city',
    highlights: ['Big Ben', 'Tower Bridge', 'British Museum', 'Buckingham Palace', 'London Eye'],
    coordinates: { lat: 51.5074, lng: -0.1278 },
    currency: 'GBP',
    language: 'English',
    timeZone: 'GMT'
  },
  {
    id: 'dubai-uae',
    name: 'Dubai',
    country: 'United Arab Emirates',
    description: 'Futuristic city in the desert with luxury shopping, ultramodern architecture.',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
    rating: 4.7,
    visitorsCount: '16M annually',
    bestTime: 'November to March',
    category: 'city',
    highlights: ['Burj Khalifa', 'Dubai Mall', 'Palm Jumeirah', 'Dubai Marina', 'Gold Souk'],
    coordinates: { lat: 25.2048, lng: 55.2708 },
    currency: 'AED',
    language: 'Arabic',
    timeZone: 'GST'
  },
  {
    id: 'santorini-greece',
    name: 'Santorini',
    country: 'Greece',
    description: 'Stunning volcanic island famous for white-washed buildings and spectacular sunsets.',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    rating: 4.9,
    visitorsCount: '2M annually',
    bestTime: 'April to October',
    category: 'beach',
    highlights: ['Oia Sunset', 'Blue Domes', 'Red Beach', 'Fira Town', 'Ancient Akrotiri'],
    coordinates: { lat: 36.3932, lng: 25.4615 },
    currency: 'EUR',
    language: 'Greek',
    timeZone: 'EET'
  },
  {
    id: 'rome-italy',
    name: 'Rome',
    country: 'Italy',
    description: 'Eternal City with ancient ruins, Vatican City, and incredible Italian cuisine.',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80',
    rating: 4.8,
    visitorsCount: '10M annually',
    bestTime: 'April to June, September to October',
    category: 'cultural',
    highlights: ['Colosseum', 'Vatican City', 'Trevi Fountain', 'Roman Forum', 'Pantheon'],
    coordinates: { lat: 41.9028, lng: 12.4964 },
    currency: 'EUR',
    language: 'Italian',
    timeZone: 'CET'
  },
  {
    id: 'istanbul-turkey',
    name: 'Istanbul',
    country: 'Turkey',
    description: 'Transcontinental city bridging Europe and Asia with rich Byzantine and Ottoman history.',
    image: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=800&q=80',
    rating: 4.4,
    visitorsCount: '13M annually',
    bestTime: 'April to May, September to October',
    category: 'cultural',
    highlights: ['Hagia Sophia', 'Blue Mosque', 'Grand Bazaar', 'Topkapi Palace', 'Bosphorus'],
    coordinates: { lat: 41.0082, lng: 28.9784 },
    currency: 'TRY',
    language: 'Turkish',
    timeZone: 'TRT'
  },
  {
    id: 'maldives',
    name: 'Maldives',
    country: 'Maldives',
    description: 'Tropical paradise with crystal-clear waters, overwater bungalows, and pristine beaches.',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80',
    rating: 4.8,
    visitorsCount: '1.7M annually',
    bestTime: 'November to April',
    category: 'beach',
    highlights: ['Overwater Villas', 'Coral Reefs', 'Water Sports', 'Spa Resorts', 'Island Hopping'],
    coordinates: { lat: 3.2028, lng: 73.2207 },
    currency: 'MVR',
    language: 'Dhivehi',
    timeZone: 'MVT'
  },
  {
    id: 'mumbai-india',
    name: 'Mumbai',
    country: 'India',
    description: 'Financial capital of India, Bollywood hub with colonial architecture and street food.',
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&q=80',
    rating: 4.3,
    visitorsCount: '7M annually',
    bestTime: 'November to February',
    category: 'city',
    highlights: ['Gateway of India', 'Marine Drive', 'Bollywood Studios', 'Chhatrapati Shivaji Terminus', 'Dharavi'],
    coordinates: { lat: 19.0760, lng: 72.8777 },
    currency: 'INR',
    language: 'Hindi',
    timeZone: 'IST'
  },
  {
    id: 'kerala-india',
    name: 'Kerala',
    country: 'India',
    description: 'God\'s Own Country with backwaters, hill stations, spice plantations, and beaches.',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    rating: 4.7,
    visitorsCount: '1M annually',
    bestTime: 'October to March',
    category: 'cultural',
    highlights: ['Alleppey Backwaters', 'Munnar Tea Gardens', 'Kovalam Beach', 'Periyar Wildlife', 'Fort Kochi'],
    coordinates: { lat: 10.8505, lng: 76.2711 },
    currency: 'INR',
    language: 'Malayalam',
    timeZone: 'IST'
  },
  {
    id: 'goa-india',
    name: 'Goa',
    country: 'India',
    description: 'Beach paradise with Portuguese heritage, vibrant nightlife, and laid-back culture.',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
    rating: 4.4,
    visitorsCount: '8M annually',
    bestTime: 'November to March',
    category: 'beach',
    highlights: ['Baga Beach', 'Old Goa Churches', 'Dudhsagar Falls', 'Anjuna Flea Market', 'Spice Plantations'],
    coordinates: { lat: 15.2993, lng: 74.1240 },
    currency: 'INR',
    language: 'Hindi',
    timeZone: 'IST'
  },
  {
    id: 'rajasthan-india',
    name: 'Rajasthan',
    country: 'India',
    description: 'Land of kings with magnificent palaces, desert landscapes, and rich cultural heritage.',
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80',
    rating: 4.5,
    visitorsCount: '5M annually',
    bestTime: 'October to March',
    category: 'cultural',
    highlights: ['Amber Fort Jaipur', 'City Palace Udaipur', 'Thar Desert', 'Hawa Mahal', 'Mehrangarh Fort'],
    coordinates: { lat: 27.0238, lng: 74.2179 },
    currency: 'INR',
    language: 'Hindi',
    timeZone: 'IST'
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    description: 'Modern city-state known for its cleanliness, diverse culture, and amazing food scene.',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80',
    rating: 4.6,
    visitorsCount: '18M annually',
    bestTime: 'February to April',
    category: 'city',
    highlights: ['Marina Bay Sands', 'Gardens by the Bay', 'Sentosa Island', 'Clarke Quay', 'Chinatown'],
    coordinates: { lat: 1.3521, lng: 103.8198 },
    currency: 'SGD',
    language: 'English',
    timeZone: 'SGT'
  }
];

export default realDestinations;